version: "3.5"
services:
  zk1:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zk1
    networks:
      - confluent
    ports:
      - 7071:7071
    volumes:
      - ./agent:/agent
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
      KAFKA_OPTS: "-javaagent:/agent/jmx_prometheus_javaagent-0.3.1.jar=7071:/agent/zookeeper.yaml"

  zk2:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zk2
    networks:
      - confluent
    ports:
      - 7072:7071
    volumes:
      - ./agent:/agent
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
      KAFKA_OPTS: "-javaagent:/agent/jmx_prometheus_javaagent-0.3.1.jar=7071:/agent/zookeeper.yaml"

  zk3:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zk3
    networks:
      - confluent
    ports:
      - 7073:7071
    volumes:
      - ./agent:/agent
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
      KAFKA_OPTS: "-javaagent:/agent/jmx_prometheus_javaagent-0.3.1.jar=7071:/agent/zookeeper.yaml"

  prometheus:
    image: prom/prometheus:v2.5.0
    networks:
      - confluent
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:3.0.1
    networks:
      - confluent
    ports:
      - 3000:3000/tcp

networks:
  confluent:
