version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zookeeper
    networks:
      - app-net
    ports:
      - 39999:39999
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JMX_PORT: 39999
      KAFKA_JMX_HOSTNAME: 127.0.0.1
  
  kafka:
    image: "confluentinc/cp-enterprise-kafka:5.1.1"
    hostname: kafka
    networks:
      - app-net
    ports:
      - 49999:49999
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_JMX_PORT: 49999
      KAFKA_JMX_HOSTNAME: 127.0.0.1

  schema-registry:
    image: "confluentinc/cp-schema-registry:5.1.1"
    hostname: schema-registry
    networks:
      - app-net
    ports:
      - 59999:59999
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_JMX_PORT: 59999
      SCHEMA_REGISTRY_JMX_HOSTNAME: 127.0.0.1

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.1.1
    hostname: control-center
    restart: always
    networks:
      - app-net
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  burrow:
    image: gnschenker/burrow:latest
    hostname: burrow
    restart: always
    volumes:
      - ${PWD}/docker-config:/etc/burrow/
      - ${PWD}/tmp:/var/tmp/burrow
    networks: 
      - app-net
    ports:
      - 8000:8000

networks:
  app-net:
